version: "3.3"
services:
  backend:
    build: 
      context: "../"
      dockerfile: "./deploy/Dockerfile.be"
    image: "backend:v2"
    #container_name: backend
    volumes:
      - ../:/home/ubuntu/main/corona-tracker/backend
    restart: always
    ports:
      - "8080"
    depends_on:
      - nginx
      - redis

  frontend:
    build: 
      context: "../"
      dockerfile: "./deploy/Dockerfile.fe"
    image: "frontend:v2"
    #container_name: frontend
    restart: always
    ports:
      - "8000"
    depends_on:
      - nginx
      - redis
      - backend
  nginx:
    image: "nginx"
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "80:80"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
